name: prompt-testing-blog
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - typer
  - langchain<=0.0.312
  - black
  - restrictedpython
  - pip:
      - promptimize
      - llama-index<0.8.31
      - sentence-transformers